### ISSUE TITLE
Bug in Proposition I.XVI

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#28]
en:1905, ru:1903 — we should not be producing `\drawUnitLine{AC,CF}` but `\drawUnitLine{BE,EC}`.

**Comment by jemmybutton** [comment]
Thank you, fixed: https://github.com/jemmybutton/byrne-euclid/commit/65f086cf1085994504bfb164c9c93af024d4bbfd#diff-ce29b5befc0686b45157d97a74d17263R1906
and
https://github.com/jemmybutton/byrne-euclid/commit/65f086cf1085994504bfb164c9c93af024d4bbfd#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1904
btw, that's why i want blue to be lighter than in the original
