### ISSUE TITLE
Fell types; unicode-math

### ISSUE THREAD

**Issue by skalyan91** [jemmybutton/byrne-euclid#34]
I really like this project! I just have a couple of suggestions:

1. The original book uses (some of) the “Fell Types”, which have been revived by Igino Marini, and are available for free: http://iginomarini.com/fell/the-revival-fonts/. (Note that the ornaments, in particular, match exactly.) I would recommend using these fonts (taking optical sizes into account) rather than Gentium, which looks a bit anachronistic.
2. I would strongly recommend using the unicode-math package (assuming it works with ConTeXt), so that the letters in math mode are in the same font as in text mode.

**Comment by jemmybutton** [comment]
Thank you! I didn't know about these fonts, they seem to be really nice. And they are not very difficult to switch to: https://github.com/jemmybutton/byrne-euclid/commit/2ac413d33700dec169dee6481c2017d6222d1aca#diff-b44801cabf4c040d727c2524313832c6R220
![imfell_1_red](https://user-images.githubusercontent.com/7447349/40078415-22426f5c-588d-11e8-9ad7-6d975bc844fa.png)
However, there are some issues that prevent me from switching completely at the moment. 
Some of the math symbols are missing and I'm not sure how to deal with it nicely (looks like the author forbids font modification in the license). It wouldn't be a problem if I could find math font with symbols that look good with this font, though (Gentium doesn't have these symbols either, but foreign ones look ok with it).
![imfell_2_red](https://user-images.githubusercontent.com/7447349/40078787-5a6c52ca-588e-11e8-93da-18dd65bddba1.png)
The more serious problem is that there's no cyrillic script and it's difficult for me to work on translation when fonts are very different (that's one of the main reasons why i chose Gentium).
So I'm inclined to use these fonts a little later, when I'll be working on replicating original lettrines (or looking for them).

Most likely unicode-math won't work with ConTeXt. Do you mean, change only the letters in math mode but keep other symbols? I'll try to find a way to do it.

**Comment by skalyan91** [comment]
For the missing math symbols and Cyrillic, I would recommend looking at [EB Garamond](https://github.com/georgd/EB-Garamond) and [Garamond Math](https://github.com/YuanshengZhao/Garamond-Math). You may have to use some sort of fake-bold to get the weights to match, though.

It would probably be fine to just change the letters in math mode, and keep other symbols; but of course using matching math symbols would be even better.

**Comment by skalyan91** [comment]
A bonus with the Fell typefaces is that they implement long s correctly, so you can turn this on and off by just switching a single OpenType feature.

**Comment by jemmybutton** [comment]
EB Garamond looks good, thank you! I'll play with it and try to switch to it some time soon.

**Comment by jemmybutton** [comment]
The font is changed to EB Garamond ( https://github.com/jemmybutton/byrne-euclid/commit/a9ec3f07fbdf7832b2f5d45649f105f6debb4492#diff-b44801cabf4c040d727c2524313832c6R411 ). Note that the secondary font for math symbols is not Garamond Math, because the whole thing to work with TeX Live "out of the box" if possible. Letters and numbers in math mode are set in EB G., but math symbols are set an some secondary font.
![eb-be_1](https://user-images.githubusercontent.com/7447349/40390969-8cff6a38-5e1f-11e8-8325-b67bce57dec4.png)
Latin Modern seems a bit too thin for the task: 
![eb-be_2](https://user-images.githubusercontent.com/7447349/40391007-a5424b60-5e1f-11e8-8da4-64b9e07d3d7d.png)
But I'll try to find something better in near future;

**Comment by skalyan91** [comment]
Looks great!

There is some advice I was able to find on using Unicode math fonts with ConTeXt: https://tex.stackexchange.com/a/172245. But it seems much more complicated than with XeLaTeX (which I normally use).

**Comment by jemmybutton** [comment]
Currently I want the book to be as easy to compile as possible so anyone with full TeX Live installation could play with it, i. e. any extra step, like installing a font, is something I want to avoid. I'd leave MathDesign Garamond as an option (most likely i'll write separate typescript for that) until Garamond Math makes its way to TeX Live.
On the other hand, Fell types fonts fit this book really well, so at some point, when all (or most of) the mistakes and typos will be corrected, I (or somebody else) will make separate English version of the book with it.

**Comment by mciura** [comment]
FWIW, I can compile the books with TeX Live on Ubuntu 16.04 while on Ubuntu 18.04 some math symbols are missing and some are typeset wrong. I have these installed on Ubuntu 18.04:
```
fonts-ebgaramond/bionic,bionic,now 0.016-1 all [installed]
  EB Garamond OpenType fonts

fonts-ebgaramond-extra/bionic,bionic,now 0.016-1 all [installed,automatic]
  EB Garamond Initials and TrueType fonts

texlive-fonts-extra/bionic,bionic,now 2017.20180305-2 all [installed]
  TeX Live: Additional fonts
```
What @skalyan91 suggests is to add the OTF or TTF files of EB Garamond and Garamond Math directly into your repository and use them rather than the files coming with TeX Live. This way, you can both have math fonts fully uniform with text fonts and achieve more independence from a particular installation.

**Comment by jemmybutton** [comment]
@mciura In my typescript, Bonum is used for most of the math symbols so the problem must be in it. As of this January, however, garamond-math is finally on CTAN https://ctan.org/pkg/garamond-math and in TeX Live, so as soon as i update, i'll gladly switch to it, leaving most of the complications behind. I really don't want to include fonts directly into the repository, but it seems necessary to have some instructions on where to put them (here https://github.com/jemmybutton/byrne-euclid/issues/41#issuecomment-503086639 @SimonGr3dal can't even get the book together, probably because of font issues, which i can't reproduce yet).

**Comment by mciura** [comment]
Thank you. FWIW, I have not installed `texlive-full` on the bad Ubuntu but I do have Bonum in
```
fonts-texgyre/bionic,bionic,now 20160520-1 all [installed]
  OpenType fonts based on URW Fonts
```

**Comment by mciura** [comment]
Also, now I understand that, unlike e.g. Xe(La)TeX, ConTeXt cannot simply use fonts from the current directory, which is what I and probably @skalyan91 silently assumed.

**Comment by jemmybutton** [comment]
@mciura From what I see now, the problem is that for some reason all my fallbacks from Bonum to EB Garamond https://github.com/jemmybutton/byrne-euclid/blob/master/type-ebgaramond-be.tex#L27 stopped working after updating to Ubuntu 18.04 and TeX Live 2017. The fonts themselves are ok, it's something in ConTeXt that went wrong. I'm working on it.

**Comment by jemmybutton** [comment]
@mciura interestingly, this doesn't happen in TeX Live 2019, everything works there as expected, except for EB Garamond font there seems to come from a different source (i assume, from here https://github.com/octaviopardo/EBGaramond12/tree/master/fonts/ ) than before (probably from here https://bitbucket.org/georgd/eb-garamond/downloads/ ) and as a result all the filenames have changed from the ones still specified for EB Garamond in ConTeXt (simply installing the font on the system fixes this). This probably means that ConTeXt seriously lags behind at EB Garamond support and even with TeX Live 2019 a custom typescript would be necessary.

**Comment by skalyan91** [comment]
@mciura Yes, that is what I assumed (I haven’t used ConTeXt before, only XeLaTeX).

**Comment by jemmybutton** [comment]
@mciura The issue with math symbols in TeX Live 2017 seems to be fixed by this tiny modification https://github.com/jemmybutton/byrne-euclid/commit/0d756a07ae4bd7ff1c1b563143d6d9f8ef997635#diff-63fb933350f13b00e136cd8011d45a63R19
Why is that i can't tell.

**Comment by mciura** [comment]
@jemmybutton I confirm that applying this change fixed my problems with math symbols. Thank you!
