### ISSUE TITLE
Enlarge narrow angles

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#7]
Privet, Sergey.  This is not a bug, just a suggestion how to improve your excellent edition.  You might consider increasing the length of the sides in narrow acute angles.  To see what I mean, please compare the yellow and blue angles on page 32 of byrne_context.pdf with their equivalents on Byrne's page 4: https://archive.org/stream/firstsixbooksofe00eucl#page/4/mode/2up

I attach an image I made with a simple formula (the formula is copied from my XeLaTeX code so the variable names probably do not match yours):

\pgfmathgreater{\angle}{60}
\pgfmathifthenelse
    {\pgfmathresult}
    {\sidelength}
    {\sidelength * (90 - \angle) / 60}

Caveat: you will probably want to keep the non-scaled way of displaying for adjacent angles that share their sides.
![Proposition 1.4](https://user-images.githubusercontent.com/1486557/30406585-fd0cfbf8-98f2-11e7-8a5e-bb43ff293a80.png)

**Comment by jemmybutton** [comment]
Hi, Mciura! Thank you, this is a great idea. It can be done by hand now (or by adding some simple macro, that would draw resized angle instead of ordinary), but I'd rather automate this. I guess, the right method to implement this feature is by changing the way angles are now drawn. Currently, they are drawn one by one, and there's no way of knowing in advance which one has adjacent angles and which one hasn't. So, it would be adequate to define all the angles first, making a list of them, then automatically compose all the blocks of adjacent angles and then draw these blocks of adjacent angles resized accordingly (maybe it would also be good to downscale larger angle blocks a little). I'll try to do it in the near future.

**Comment by jemmybutton** [comment]
@mciura And the first version is here [https://github.com/jemmybutton/byrne-euclid/commit/ff094da5aadd00291eb990986431d1ac857c6eba](url)
Before and after comparison:
![anglesizecompensation](https://user-images.githubusercontent.com/7447349/30458501-8bdef05e-99b4-11e7-9b80-8ed922f71c97.png)
To get this working, instead of
```
draw byAngle(A, B, C, byyellow, 0);
draw byAngle(B, C, A, byblue, 0);
draw byAngle(C, A, B, byred, 0);
```
one should type
```
byAngleDefine(A, B, C, byyellow, 0);
byAngleDefine(B, C, A, byblue, 0);
byAngleDefine(C, A, B, byred, 0);
draw byNamedAngleResized;
```
I'll play a little with the compensation function (now it's kind of a random thing `(1 + 3/4cosd(v)**2)` for angles less than 180 degrees) and migrate all the pictures to the new method.

**Comment by jemmybutton** [comment]
There's angle size compensation everywhere in the book now [https://github.com/jemmybutton/byrne-euclid/commit/f38d6aaf0bdd858f439bcf97b6b8637468bb7971](url). It may require some tweaking, but in general everything seems to work ok.
[byrne_context.pdf](https://github.com/jemmybutton/byrne-euclid/files/1309427/byrne_context.pdf)
