### ISSUE TITLE
[Nit] Consider changing the shade of yellow and possibly blue

### ISSUE THREAD

**Issue by MarcinCiura** [jemmybutton/byrne-euclid#9]
Hi Sergey.  I am merely relaying [a Reddit comment](https://www.reddit.com/r/math/comments/73gbti/open_source_reedition_of_oliver_byrnes_the_first/dnqc2vd/) about the shades of yellow and blue in your book.  Although I tend to agree with /u/jacobolus that the yellow might be warmer, this is a matter of taste so the ultimate call is yours.
As a side note, I checked your colours against deuteranopia, protanopia, and tritanopia with [Vischeck](http://www.vischeck.com/vischeck/).  The good news is that all colorblind people can distinguish its colors.  Here is how a deuteranope sees it: 
![deuteranope](https://user-images.githubusercontent.com/1486557/31052356-ae69b6a6-a682-11e7-8b45-74b0c26e20aa.jpg)

**Comment by jemmybutton** [comment]
Hi Mciura. The colours are currently more like placeholders for colours to be. Simply picking them from the scanned Byrne's original didn't work for me (because, for example, blue is too dark and is easily confused with black), so I just defined them to be dissimilar enough to be easily identified during proof-reading. Otherwise, I agree and have [changed them a little](https://github.com/jemmybutton/byrne-euclid/commit/bb86932e2ca910930cb8208ada314647f64e4876), to look nicer (hopefully). Thank for the link to Vischeck!
[byrne_context.pdf](https://github.com/jemmybutton/byrne-euclid/files/1347202/byrne_context.pdf)
I am not closing this issue yet, because my laptop screen may not be the best to judge colours.

**Comment by mciura** [comment]
Don't you need to change [these color definitions](https://github.com/jemmybutton/byrne-euclid/blob/master/preamble_be.tex#L308), too?

**Comment by jemmybutton** [comment]
You're right, I just forgot about this (fixed). These definitions only affect coloured letters in the fifth book. It's actually possible to define metapost colors from ConTeXt, but I didn't do it because I thought it would be better to make mp code more or less independent from ConTeXt code, but maybe it doesn't matter any more.

**Comment by jrus** [comment]
I’m just eyeballing the Taschen book (in which colors vary a bit, and I’m going for something probably a bit more colorful), but let me recommend the sRGB colors:

red: d84737
yellow: eeb131
blue: 025e97
black: 342920

**Comment by jemmybutton** [comment]
Hi, Jacob. Thank you! I've changed the colours a little, they are now much closer to yours, probably. But I still like blue to be a little bit lighter (sometimes it looks too close to black in Byrne's book for me). I suspect that it's not just difference in lightness that matters, but difference in lightness between colours relative to  difference in lightness between them and the background, i. e. darker colours look more similar against lighter backgrounds than against darker ones, other things being equal. I've also added a new colour for black (called `byblack`) and it is used throughout the book, and even though it is now equal to regular black, it is easy to change it to some sort of dark grey without messing with the definition of black. I'll leave the background white for now, but will consider changing it when I'll have better understanding of how the book can actually be used.
See [here](https://github.com/jemmybutton/byrne-euclid/commit/1300c505cb7dd3fca581e735d9ca1d4a8166c955)
[byrne_context.pdf](https://github.com/jemmybutton/byrne-euclid/files/1350246/byrne_context.pdf)
